#!/usr/bin/env python3
"""
SGOU Academic Database — Automated XML Sitemap & SEO Index Generator
Generates high-coverage XML sitemaps covering all 37 programmes, 1,200+ courses,
degree categories, and viewer endpoints, conforming to Google & Bing sitemap standards.
"""

import os
import json
import xml.etree.ElementTree as ET
from xml.dom import minidom
from datetime import date

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_URL = "https://sgou-slm-database.vercel.app"
TODAY = date.today().isoformat()

def prettify_xml(elem):
    """Return a pretty-printed XML string for the Element."""
    rough_string = ET.tostring(elem, encoding="utf-8")
    reparsed = minidom.parseString(rough_string)
    # Remove extra blank lines generated by minidom
    lines = [line for line in reparsed.toprettyxml(indent="  ").split("\n") if line.strip()]
    return "\n".join(lines) + "\n"

def generate_sitemaps():
    print("Generating comprehensive XML Sitemaps for SGOU Academic Database...")

    # Load data
    slm_path = os.path.join(REPO_ROOT, "data", "sgou_slm_data.json")
    q_path = os.path.join(REPO_ROOT, "data", "sgou_questions_cleaned.json")

    with open(slm_path, encoding="utf-8") as f:
        slm_data = json.load(f)

    with open(q_path, encoding="utf-8") as f:
        q_data = json.load(f)

    # -------------------------------------------------------------------------
    # 1. Main & Category Sitemap (sitemap-main.xml)
    # -------------------------------------------------------------------------
    urlset_main = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9",
                             attrib={"xmlns:image": "http://www.google.com/schemas/sitemap-image/1.1"})

    main_urls = [
        {"loc": f"{BASE_URL}/", "priority": "1.0", "changefreq": "daily", "title": "SGOU Academic Database — SLM Textbooks, PYQs & Assignments"},
        {"loc": f"{BASE_URL}/?type=slm", "priority": "0.9", "changefreq": "daily", "title": "SGOU Self-Learning Material (SLM) Textbooks"},
        {"loc": f"{BASE_URL}/?type=pyq", "priority": "0.9", "changefreq": "daily", "title": "SGOU Previous Year Exam Question Papers (PYQ)"},
        {"loc": f"{BASE_URL}/?type=assignment", "priority": "0.9", "changefreq": "daily", "title": "SGOU Continuous Assessment Assignment Booklets"},
        {"loc": f"{BASE_URL}/?level=fyug", "priority": "0.9", "changefreq": "weekly", "title": "SGOU Four Year Undergraduate Programmes (FYUG)"},
        {"loc": f"{BASE_URL}/?level=ug", "priority": "0.9", "changefreq": "weekly", "title": "SGOU Undergraduate Programmes (UG)"},
        {"loc": f"{BASE_URL}/?level=pg", "priority": "0.9", "changefreq": "weekly", "title": "SGOU Postgraduate Programmes (PG)"},
        {"loc": f"{BASE_URL}/view.html", "priority": "0.8", "changefreq": "weekly", "title": "SGOU Document Reader & PDF Viewer"},
        {"loc": f"{BASE_URL}/llms.txt", "priority": "0.7", "changefreq": "monthly", "title": "SGOU Academic Database AI Machine-Readable Index"},
    ]

    for item in main_urls:
        url_el = ET.SubElement(urlset_main, "url")
        ET.SubElement(url_el, "loc").text = item["loc"]
        ET.SubElement(url_el, "lastmod").text = TODAY
        ET.SubElement(url_el, "changefreq").text = item["changefreq"]
        ET.SubElement(url_el, "priority").text = item["priority"]
        if "title" in item:
            img_el = ET.SubElement(url_el, "image:image")
            ET.SubElement(img_el, "image:loc").text = f"{BASE_URL}/assets/images/og-image.png"
            ET.SubElement(img_el, "image:title").text = item["title"]

    main_xml_path = os.path.join(REPO_ROOT, "sitemaps", "sitemap-main.xml")
    with open(main_xml_path, "w", encoding="utf-8") as f:
        f.write(prettify_xml(urlset_main))
    print(f"  [+] Wrote sitemap-main.xml ({len(main_urls)} URLs)")

    # -------------------------------------------------------------------------
    # 2. Programmes Sitemap (sitemap-programmes.xml)
    # -------------------------------------------------------------------------
    urlset_prog = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    prog_count = 0

    for prog in slm_data:
        p_name = prog.get("programme_name", "").strip()
        p_level = prog.get("level", "UG").strip().lower()
        if not p_name:
            continue

        prog_count += 1
        # Deep links for programme on main site
        encoded_name = urllib_quote = p_name.replace(" ", "%20")
        
        # Programme landing link
        url_el = ET.SubElement(urlset_prog, "url")
        ET.SubElement(url_el, "loc").text = f"{BASE_URL}/?search={encoded_name}"
        ET.SubElement(url_el, "lastmod").text = TODAY
        ET.SubElement(url_el, "changefreq").text = "weekly"
        ET.SubElement(url_el, "priority").text = "0.85"

    prog_xml_path = os.path.join(REPO_ROOT, "sitemaps", "sitemap-programmes.xml")
    with open(prog_xml_path, "w", encoding="utf-8") as f:
        f.write(prettify_xml(urlset_prog))
    print(f"  [+] Wrote sitemap-programmes.xml ({prog_count} URLs)")

    # -------------------------------------------------------------------------
    # 3. Courses & Materials Sitemap (sitemap-courses.xml)
    # -------------------------------------------------------------------------
    urlset_courses = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    seen_codes = set()
    course_count = 0

    for prog in slm_data:
        for sem in prog.get("semesters", []):
            for c in sem.get("courses", []):
                code = c.get("code", "").strip()
                if not code or code in seen_codes:
                    continue
                seen_codes.add(code)
                course_count += 1

                # Clean course deep link
                url_el1 = ET.SubElement(urlset_courses, "url")
                ET.SubElement(url_el1, "loc").text = f"{BASE_URL}/?course={code}"
                ET.SubElement(url_el1, "lastmod").text = TODAY
                ET.SubElement(url_el1, "changefreq").text = "weekly"
                ET.SubElement(url_el1, "priority").text = "0.75"

                # Dedicated clean viewer link
                url_el2 = ET.SubElement(urlset_courses, "url")
                ET.SubElement(url_el2, "loc").text = f"{BASE_URL}/view/{code}"
                ET.SubElement(url_el2, "lastmod").text = TODAY
                ET.SubElement(url_el2, "changefreq").text = "weekly"
                ET.SubElement(url_el2, "priority").text = "0.70"

    courses_xml_path = os.path.join(REPO_ROOT, "sitemaps", "sitemap-courses.xml")
    with open(courses_xml_path, "w", encoding="utf-8") as f:
        f.write(prettify_xml(urlset_courses))
    print(f"  [+] Wrote sitemap-courses.xml ({course_count * 2} URLs)")

    # -------------------------------------------------------------------------
    # 4. Root Sitemap Index (sitemap.xml)
    # -------------------------------------------------------------------------
    sitemapindex = ET.Element("sitemapindex", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")

    sitemaps = [
        f"{BASE_URL}/sitemaps/sitemap-main.xml",
        f"{BASE_URL}/sitemaps/sitemap-programmes.xml",
        f"{BASE_URL}/sitemaps/sitemap-courses.xml"
    ]

    for sm_url in sitemaps:
        sm_el = ET.SubElement(sitemapindex, "sitemap")
        ET.SubElement(sm_el, "loc").text = sm_url
        ET.SubElement(sm_el, "lastmod").text = TODAY

    root_sitemap_path = os.path.join(REPO_ROOT, "sitemap.xml")
    with open(root_sitemap_path, "w", encoding="utf-8") as f:
        f.write(prettify_xml(sitemapindex))
    print(f"  [+] Wrote root sitemap.xml index pointing to all 3 sub-sitemaps")
    print(f"Total indexed URLs across platform: {len(main_urls) + prog_count + (course_count * 2)}")

if __name__ == "__main__":
    generate_sitemaps()
